<script src="/js/jquery.dataTables.min.js"></script>
<script>
    $(document).ready(function() {
        $("table a").tooltip();
        $("#tabela").dataTable();
    });
</script>
<style>
    .dataTables_filter,.dataTables_length{
        width:40%;
        float:left;
    }
    #tabela_info{
        width:45%;
        float:left;
    }
    #tabela
    {
        width:100%;
        float:left;
    }
    #tabela th
    {
        cursor: pointer;
    }

    #tabela_paginate{
        float:left;
        width:40%;
    }
    #tabela_paginate a{
        float:left;
        width:20%;
        cursor: pointer;
    }
</style>
<?php if ($this->messages):
    ?>
    <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>       
        <?php foreach ($this->messages as $messages): ?>
            <strong>Success!</strong> <?php echo $messages ?>       
        <?php endforeach; ?>
    </div>
<?php endif; ?>
<div class="row-fluid">

   
    <div class="span12">
        <table id="tabela" class="table table-striped table-bordered table-hover">
            <thead>         
                <tr>

                    <th>Solicitante</th>
                    <th>Colaborador</th>
                    <th>Data da solicitação</th>                   
                    <th>Início da tarefa</th>                   
                    <th>Término da tarefa</th>                   
                    <th>Motivo</th>
                   
                    
                    <th>Opções</th>
                    

                </tr>
            </thead>
            <tbody>
                <?php
             
                foreach ($this->lista as $usuario): ?>
                    <tr>

                        <td><?php echo $usuario->getSolicitante(); ?></td>
                        <td><?php echo $usuario->getNome(); ?></td>
                        <td><?php echo $usuario->getDataregistro();; ?></td>
                        <td><?php echo $usuario->getDatainicio(); ?></td>
                        <td><?php echo $usuario->getDatafim(); ?></td>
                        <td><?php echo $usuario->getMotivo(); ?></td>
                        
                      
                        <td>
                            <a href="<?php echo $this->url('convite-hora-extra/aprovar',array('id'=>$usuario->getIdconvitehoraextra()));?>" class="btn" data-toggle="tooltip" title="Aprovar convite" ><i class="icon-thumbs-up"></i></a>
                            <a href="<?php echo $this->url('convite-hora-extra/negar',array('id'=>$usuario->getIdconvitehoraextra()));?>" class="btn" data-toggle="tooltip" title="Negar convite" ><i class="icon-thumbs-down"></i></a>
                        </td>
                                           
                       
                    </tr>
                <?php endforeach; ?>

            </tbody>
            <tfoot>
                <tr>
                    <td colspan="7">
                        <a class="btn" href="<?php echo $this->url('convite-hora-extra/single-store');?>"  data-toggle="tooltip" title="Novo Convite Individual" ><i class="icon-user"></i></a>
                        <a class="btn" href="<?php echo $this->url('convite-hora-extra/group-store');?>"  data-toggle="tooltip" title="Novo Convite Coletivo" ><i class="icon-th"></i></a>
                    </td>
                </tr>
            </tfoot>
            

        </table>
    </div>
</div>