<script src="/js/jquery.dataTables.min.js"></script>
<script>
    $(document).ready(function() {
        $("table a").tooltip();
        $("#tabela").dataTable();
    });
</script>
<style>
    .dataTables_filter,.dataTables_length{
        width:40%;
        float:left;
    }
    #tabela_info{
        width:45%;
        float:left;
    }
    #tabela
    {
        width:100%;
        float:left;
    }
    #tabela th
    {
        cursor: pointer;
    }

    #tabela_paginate{
        float:left;
        width:40%;
    }
    #tabela_paginate a{
        float:left;
        width:20%;
        cursor: pointer;
    }
</style>
<?php if ($this->messages):
    ?>
    <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>       
        <?php foreach ($this->messages as $messages): ?>
            <strong>Success!</strong> <?php echo $messages ?>       
        <?php endforeach; ?>
    </div>
<?php endif; ?>
<div class="row-fluid">

    <div class="span3">
        <?php
        include_once(__DIR__ . '/../menu.phtml');
        ?>


    </div>
    <div class="span9">
        <table id="tabela" class="table table-striped table-bordered table-hover">
            <thead>         
                <tr>

                    <th>Solicitante</th>
                    <th>Data da solicitação</th>                   
                    <th>Início da tarefa</th>                   
                    <th>Término da tarefa</th>                   
                    <th>Matrícula</th>
                    <th>Colaborador</th>



                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->lista as $usuario): ?>
                    <tr>

                        <td><?php echo $usuario->getSolicitante(); ?></td>
                        <td><?php echo $usuario->getDataregistro();
                ; ?></td>
                        <td><?php echo $usuario->getDatainicio(); ?></td>
                        <td><?php echo $usuario->getDatafim(); ?></td>
                        <td><?php echo $usuario->getMatricula(); ?></td>
                        <td><?php echo $usuario->getNome() ?></td>



                    </tr>
                <?php endforeach; ?>

            </tbody>
            <tfoot>
                <tr>
                    <td colspan="6">
                        <a class='btn' href="<?php echo $this->url('departamento-pessoal/convite-hora-extra/exportar');?>" title='Fazer download da tabela'><i class="icon-download-alt"></i></a>
                    </td>
                </tr>
            </tfoot>


        </table>
    </div>
</div>